<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Rox.Core/Rox.Core.csproj" />
    <ProjectReference Include="../../src/Rox.Profile/Rox.Profile.csproj" />
    <ProjectReference Include="../../src/Rox.FlowEngine/Rox.FlowEngine.csproj" />
    <ProjectReference Include="../../src/Rox.Simulator/Rox.Simulator.csproj" />
    <ProjectReference Include="../../src/Rox.Transport/Rox.Transport.csproj" />
    <ProjectReference Include="../../src/Rox.Uds/Rox.Uds.csproj" />
    <ProjectReference Include="../../src/Rox.Diagnostics/Rox.Diagnostics.csproj" />
    <ProjectReference Include="../../src/Rox.Security/Rox.Security.csproj" />
    <ProjectReference Include="../../src/Rox.KeyFunctions/Rox.KeyFunctions.csproj" />
    <ProjectReference Include="../../src/Rox.Reflash/Rox.Reflash.csproj" />
    <ProjectReference Include="../../src/Rox.Logging/Rox.Logging.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="data/**" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
