<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Serilog" Version="4.2.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
    <PackageReference Include="QuestPDF" Version="2024.12.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Rox.Core/Rox.Core.csproj" />
  </ItemGroup>
</Project>
